# fly.toml app configuration file generated for gamer-fier-bot on 2023-05-07T23:34:29-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "gamer-fier-bot"
primary_region = "atl"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
